import { withTransaction } from "../db/pool.js";
import { HttpError } from "../lib/errors.js";
import { buildMutableRuntimeState } from "../lib/runtimePlayerState.js";
import { getCityDefinition, normalizeCityId } from "../data/cityData.js";
import { getItemDefinition, getItemDisplayName, getItemSummary } from "../data/itemData.js";
import { createDefaultPlayerState, findPlayerStateByUserInternalId, upsertPlayerRuntimeState } from "../repositories/playerStateRepository.js";
import { findUserByInternalId } from "../repositories/usersRepository.js";
import { createMarketplaceListing, expireOldMarketplaceListings, findMarketplaceListingById, listMarketplaceListings, updateMarketplaceListingStatus } from "../repositories/marketplaceRepository.js";
import { getCityDemandProfile } from "./liveWorldService.js";
import { addPlayerRecord } from "./playerRecordsService.js";
function asRecord(value) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
function asNumber(value, fallback = 0) { const numeric = Number(value); return Number.isFinite(numeric) ? numeric : fallback; }
function getInventory(runtimeState) { const player = asRecord(runtimeState.player); player.inventory = { ...asRecord(player.inventory) }; runtimeState.player = player; return player.inventory; }
function addInventory(runtimeState, itemId, quantity) { const inventory = getInventory(runtimeState); inventory[itemId] = Math.max(0, Math.floor(asNumber(inventory[itemId], 0) + quantity)); }
function removeInventory(runtimeState, itemId, quantity) { const inventory = getInventory(runtimeState); const owned = Math.max(0, Math.floor(asNumber(inventory[itemId], 0))); if (owned < quantity) throw new HttpError(409, `You only have ${owned} ${getItemDisplayName(itemId)}.`, "MARKETPLACE_ITEM_INSUFFICIENT"); const next = owned - quantity; if (next > 0) inventory[itemId] = next; else delete inventory[itemId]; }
function applyGold(runtimeState, amount) { const player = runtimeState.player; const next = Math.max(0, Math.floor(asNumber(player.gold, 0) + amount)); player.gold = next; player.currencies = { ...asRecord(player.currencies), gold: next }; }
async function loadRuntimeState(client, user) { await createDefaultPlayerState(client, user.internalId); const playerState = await findPlayerStateByUserInternalId(client, user.internalId); if (!playerState) throw new HttpError(404, "Player state unavailable.", "PLAYER_STATE_NOT_FOUND"); return { playerState, runtimeState: buildMutableRuntimeState(user, playerState) }; }
function currentCityId(runtimeState) { const travel = asRecord(runtimeState.travel); const current = asRecord(runtimeState.player?.current); return normalizeCityId(travel.currentCityId ?? current.currentCityId ?? "nexis"); }
function serializeListing(listing, viewerUser = null) { const item = getItemSummary(listing.itemId); const demand = getCityDemandProfile(listing.cityId); return { id: String(listing.id), seller: { publicId: listing.sellerPublicId, name: listing.sellerName }, itemId: listing.itemId, item, quantity: listing.quantity, unitPrice: listing.unitPrice, totalPrice: listing.unitPrice * listing.quantity, cityId: listing.cityId, cityName: getCityDefinition(listing.cityId).name, status: listing.status, createdAt: listing.createdAt, expiresAt: listing.expiresAt, isOwnListing: Boolean(viewerUser && listing.sellerInternalId === viewerUser.internalId), demandTags: demand.tags, demandHeadline: demand.headline }; }
function readFilters(query = {}) { const category = typeof query.category === "string" ? query.category.trim().toLowerCase() : ""; const cityId = typeof query.cityId === "string" && query.cityId ? normalizeCityId(query.cityId, "") : ""; const rarity = typeof query.rarity === "string" ? query.rarity.trim().toLowerCase() : ""; const maxPrice = Math.max(0, Math.floor(asNumber(query.maxPrice, 0))); return { category, cityId, rarity, maxPrice }; }
function filterListing(listing, filters) { const item = getItemDefinition(listing.itemId); if (!item) return false; if (filters.category && String(item.category ?? "").toLowerCase() !== filters.category) return false; if (filters.rarity && String(item.rarity ?? "").toLowerCase() !== filters.rarity) return false; if (filters.maxPrice && listing.unitPrice > filters.maxPrice) return false; return true; }
async function buildMarketplacePayload(client, user, runtimeState, filters) { const listings = (await listMarketplaceListings(client, filters)).filter((listing) => filterListing(listing, filters)); return { listings: listings.map((listing) => serializeListing(listing, user)), filters, inventory: Object.entries(getInventory(runtimeState)).map(([itemId, quantity]) => ({ itemId, quantity: Math.floor(asNumber(quantity, 0)), item: getItemSummary(itemId) })).filter((entry) => entry.quantity > 0), cityDemand: getCityDemandProfile(currentCityId(runtimeState)) }; }
export async function getMarketplaceForUser(user, query = {}) { return withTransaction(async (client) => { await expireOldMarketplaceListings(client); const filters = readFilters(query); const { playerState, runtimeState } = await loadRuntimeState(client, user); return { playerState, marketplace: await buildMarketplacePayload(client, user, runtimeState, filters) }; }); }
export async function createMarketplaceListingForUser(user, payload = {}) { return withTransaction(async (client) => { const itemId = String(payload.itemId ?? "").trim(); const item = getItemDefinition(itemId); if (!item) throw new HttpError(404, "Item not found.", "MARKETPLACE_ITEM_NOT_FOUND"); const quantity = Math.max(1, Math.min(99, Math.floor(asNumber(payload.quantity, 1)))); const unitPrice = Math.max(1, Math.min(999999, Math.floor(asNumber(payload.unitPrice, item.valueSell ?? 1)))); const cityId = normalizeCityId(payload.cityId, "nexis"); const { runtimeState } = await loadRuntimeState(client, user); removeInventory(runtimeState, itemId, quantity); const sellerName = `${user.firstName}${user.lastName ? ` ${user.lastName}` : ""}`.trim() || "Citizen"; const listing = await createMarketplaceListing(client, { sellerInternalId: user.internalId, sellerPublicId: user.publicId, sellerName, itemId, quantity, unitPrice, cityId }); runtimeState.player.counters = { ...asRecord(runtimeState.player.counters), marketplaceListingsCreated: Math.max(0, Math.floor(asNumber(runtimeState.player.counters?.marketplaceListingsCreated, 0) + 1)) }; addPlayerRecord(runtimeState, { category: "marketplace", summary: `Listed ${getItemDisplayName(itemId)} x${quantity} for ${unitPrice} gold each.`, detail: { itemId, quantity, unitPrice, cityId }, source: "marketplace", route: "/market", timestamp: Date.now() }); const playerState = await upsertPlayerRuntimeState(client, user.internalId, runtimeState); return { playerState, listing: serializeListing(listing, user), marketplace: await buildMarketplacePayload(client, user, runtimeState, readFilters({})), message: `Listed ${getItemDisplayName(itemId)} x${quantity} for ${unitPrice} gold each.` }; }); }
export async function buyMarketplaceListingForUser(user, listingIdInput) { return withTransaction(async (client) => { const listingId = Math.max(1, Math.floor(asNumber(listingIdInput, 0))); const listing = await findMarketplaceListingById(client, listingId, { forUpdate: true }); if (!listing || listing.status !== "active" || (listing.expiresAt && listing.expiresAt <= Date.now())) throw new HttpError(404, "Marketplace listing unavailable.", "MARKETPLACE_LISTING_UNAVAILABLE"); if (listing.sellerInternalId === user.internalId) throw new HttpError(409, "You cannot buy your own listing.", "MARKETPLACE_SELF_BUY"); const { runtimeState: buyerState } = await loadRuntimeState(client, user); const totalPrice = listing.quantity * listing.unitPrice; if (asNumber(buyerState.player.gold, 0) < totalPrice) throw new HttpError(409, `Requires ${totalPrice} gold.`, "MARKETPLACE_GOLD_INSUFFICIENT"); const sellerUser = await findUserByInternalId(client, listing.sellerInternalId); if (!sellerUser) throw new HttpError(404, "Seller unavailable.", "MARKETPLACE_SELLER_MISSING"); const { runtimeState: sellerState } = await loadRuntimeState(client, sellerUser); applyGold(buyerState, -totalPrice); addInventory(buyerState, listing.itemId, listing.quantity); buyerState.player.counters = { ...asRecord(buyerState.player.counters), marketplacePurchases: Math.max(0, Math.floor(asNumber(buyerState.player.counters?.marketplacePurchases, 0) + 1)) }; addPlayerRecord(buyerState, { category: "marketplace", summary: `Bought ${getItemDisplayName(listing.itemId)} x${listing.quantity} for ${totalPrice} gold.`, detail: { listingId, itemId: listing.itemId, quantity: listing.quantity, totalPrice, sellerPublicId: listing.sellerPublicId }, source: "marketplace", route: "/market", timestamp: Date.now() }); applyGold(sellerState, totalPrice); sellerState.player.counters = { ...asRecord(sellerState.player.counters), marketplaceSales: Math.max(0, Math.floor(asNumber(sellerState.player.counters?.marketplaceSales, 0) + 1)) }; addPlayerRecord(sellerState, { category: "marketplace", summary: `Sold ${getItemDisplayName(listing.itemId)} x${listing.quantity} for ${totalPrice} gold.`, detail: { listingId, itemId: listing.itemId, quantity: listing.quantity, totalPrice, buyerPublicId: user.publicId }, source: "marketplace", route: "/market", timestamp: Date.now() }); await updateMarketplaceListingStatus(client, listing.id, "sold", { buyerInternalId: user.internalId, buyerPublicId: user.publicId, soldAt: Date.now() }); const buyerPlayerState = await upsertPlayerRuntimeState(client, user.internalId, buyerState); await upsertPlayerRuntimeState(client, sellerUser.internalId, sellerState); return { playerState: buyerPlayerState, listing: serializeListing({ ...listing, status: "sold" }, user), marketplace: await buildMarketplacePayload(client, user, buyerState, readFilters({})), message: `Bought ${getItemDisplayName(listing.itemId)} x${listing.quantity} for ${totalPrice} gold.` }; }); }
export async function cancelMarketplaceListingForUser(user, listingIdInput) { return withTransaction(async (client) => { const listingId = Math.max(1, Math.floor(asNumber(listingIdInput, 0))); const listing = await findMarketplaceListingById(client, listingId, { forUpdate: true }); if (!listing || listing.status !== "active") throw new HttpError(404, "Marketplace listing unavailable.", "MARKETPLACE_LISTING_UNAVAILABLE"); if (listing.sellerInternalId !== user.internalId) throw new HttpError(403, "Only the seller can cancel this listing.", "MARKETPLACE_NOT_SELLER"); const { runtimeState } = await loadRuntimeState(client, user); addInventory(runtimeState, listing.itemId, listing.quantity); addPlayerRecord(runtimeState, { category: "marketplace", summary: `Cancelled marketplace listing: ${getItemDisplayName(listing.itemId)} x${listing.quantity}.`, detail: { listingId, itemId: listing.itemId, quantity: listing.quantity }, source: "marketplace", route: "/market", timestamp: Date.now() }); const cancelled = await updateMarketplaceListingStatus(client, listing.id, "cancelled", { cancelledAt: Date.now() }); const playerState = await upsertPlayerRuntimeState(client, user.internalId, runtimeState); return { playerState, listing: serializeListing(cancelled, user), marketplace: await buildMarketplacePayload(client, user, runtimeState, readFilters({})), message: `Cancelled listing and returned ${getItemDisplayName(listing.itemId)} x${listing.quantity}.` }; }); }
